// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: depth.proto

#include "depth.pb.h"
#include "depth.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace depth {

static const char* DepthService_method_names[] = {
  "/depth.DepthService/DepthReq",
};

std::unique_ptr< DepthService::Stub> DepthService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DepthService::Stub> stub(new DepthService::Stub(channel));
  return stub;
}

DepthService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_DepthReq_(DepthService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DepthService::Stub::DepthReq(::grpc::ClientContext* context, const ::depth::DepthRequest& request, ::depth::DepthRsP* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_DepthReq_, context, request, response);
}

void DepthService::Stub::experimental_async::DepthReq(::grpc::ClientContext* context, const ::depth::DepthRequest* request, ::depth::DepthRsP* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DepthReq_, context, request, response, std::move(f));
}

void DepthService::Stub::experimental_async::DepthReq(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::depth::DepthRsP* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_DepthReq_, context, request, response, std::move(f));
}

void DepthService::Stub::experimental_async::DepthReq(::grpc::ClientContext* context, const ::depth::DepthRequest* request, ::depth::DepthRsP* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DepthReq_, context, request, response, reactor);
}

void DepthService::Stub::experimental_async::DepthReq(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::depth::DepthRsP* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_DepthReq_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::depth::DepthRsP>* DepthService::Stub::AsyncDepthReqRaw(::grpc::ClientContext* context, const ::depth::DepthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::depth::DepthRsP>::Create(channel_.get(), cq, rpcmethod_DepthReq_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::depth::DepthRsP>* DepthService::Stub::PrepareAsyncDepthReqRaw(::grpc::ClientContext* context, const ::depth::DepthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::depth::DepthRsP>::Create(channel_.get(), cq, rpcmethod_DepthReq_, context, request, false);
}

DepthService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DepthService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DepthService::Service, ::depth::DepthRequest, ::depth::DepthRsP>(
          std::mem_fn(&DepthService::Service::DepthReq), this)));
}

DepthService::Service::~Service() {
}

::grpc::Status DepthService::Service::DepthReq(::grpc::ServerContext* context, const ::depth::DepthRequest* request, ::depth::DepthRsP* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace depth

