// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: depth.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_depth_2eproto__INCLUDED
#define GRPC_depth_2eproto__INCLUDED

#include "depth.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace depth {

// The greeting service definition.
class DepthService final {
 public:
  static constexpr char const* service_full_name() {
    return "depth.DepthService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    virtual ::grpc::Status DepthReq(::grpc::ClientContext* context, const ::depth::DepthRequest& request, ::depth::DepthRsP* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::depth::DepthRsP>> AsyncDepthReq(::grpc::ClientContext* context, const ::depth::DepthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::depth::DepthRsP>>(AsyncDepthReqRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::depth::DepthRsP>> PrepareAsyncDepthReq(::grpc::ClientContext* context, const ::depth::DepthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::depth::DepthRsP>>(PrepareAsyncDepthReqRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Sends a greeting
      virtual void DepthReq(::grpc::ClientContext* context, const ::depth::DepthRequest* request, ::depth::DepthRsP* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DepthReq(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::depth::DepthRsP* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void DepthReq(::grpc::ClientContext* context, const ::depth::DepthRequest* request, ::depth::DepthRsP* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void DepthReq(::grpc::ClientContext* context, const ::depth::DepthRequest* request, ::depth::DepthRsP* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void DepthReq(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::depth::DepthRsP* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void DepthReq(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::depth::DepthRsP* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::depth::DepthRsP>* AsyncDepthReqRaw(::grpc::ClientContext* context, const ::depth::DepthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::depth::DepthRsP>* PrepareAsyncDepthReqRaw(::grpc::ClientContext* context, const ::depth::DepthRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status DepthReq(::grpc::ClientContext* context, const ::depth::DepthRequest& request, ::depth::DepthRsP* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::depth::DepthRsP>> AsyncDepthReq(::grpc::ClientContext* context, const ::depth::DepthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::depth::DepthRsP>>(AsyncDepthReqRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::depth::DepthRsP>> PrepareAsyncDepthReq(::grpc::ClientContext* context, const ::depth::DepthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::depth::DepthRsP>>(PrepareAsyncDepthReqRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void DepthReq(::grpc::ClientContext* context, const ::depth::DepthRequest* request, ::depth::DepthRsP* response, std::function<void(::grpc::Status)>) override;
      void DepthReq(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::depth::DepthRsP* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void DepthReq(::grpc::ClientContext* context, const ::depth::DepthRequest* request, ::depth::DepthRsP* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void DepthReq(::grpc::ClientContext* context, const ::depth::DepthRequest* request, ::depth::DepthRsP* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void DepthReq(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::depth::DepthRsP* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void DepthReq(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::depth::DepthRsP* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::depth::DepthRsP>* AsyncDepthReqRaw(::grpc::ClientContext* context, const ::depth::DepthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::depth::DepthRsP>* PrepareAsyncDepthReqRaw(::grpc::ClientContext* context, const ::depth::DepthRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_DepthReq_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status DepthReq(::grpc::ServerContext* context, const ::depth::DepthRequest* request, ::depth::DepthRsP* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_DepthReq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DepthReq() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_DepthReq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DepthReq(::grpc::ServerContext* /*context*/, const ::depth::DepthRequest* /*request*/, ::depth::DepthRsP* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDepthReq(::grpc::ServerContext* context, ::depth::DepthRequest* request, ::grpc::ServerAsyncResponseWriter< ::depth::DepthRsP>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_DepthReq<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_DepthReq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_DepthReq() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::depth::DepthRequest, ::depth::DepthRsP>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::depth::DepthRequest* request, ::depth::DepthRsP* response) { return this->DepthReq(context, request, response); }));}
    void SetMessageAllocatorFor_DepthReq(
        ::grpc::experimental::MessageAllocator< ::depth::DepthRequest, ::depth::DepthRsP>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::depth::DepthRequest, ::depth::DepthRsP>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_DepthReq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DepthReq(::grpc::ServerContext* /*context*/, const ::depth::DepthRequest* /*request*/, ::depth::DepthRsP* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* DepthReq(
      ::grpc::CallbackServerContext* /*context*/, const ::depth::DepthRequest* /*request*/, ::depth::DepthRsP* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* DepthReq(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::depth::DepthRequest* /*request*/, ::depth::DepthRsP* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_DepthReq<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_DepthReq<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_DepthReq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DepthReq() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_DepthReq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DepthReq(::grpc::ServerContext* /*context*/, const ::depth::DepthRequest* /*request*/, ::depth::DepthRsP* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_DepthReq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DepthReq() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_DepthReq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DepthReq(::grpc::ServerContext* /*context*/, const ::depth::DepthRequest* /*request*/, ::depth::DepthRsP* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDepthReq(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_DepthReq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_DepthReq() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DepthReq(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_DepthReq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DepthReq(::grpc::ServerContext* /*context*/, const ::depth::DepthRequest* /*request*/, ::depth::DepthRsP* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* DepthReq(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* DepthReq(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DepthReq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DepthReq() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::depth::DepthRequest, ::depth::DepthRsP>(std::bind(&WithStreamedUnaryMethod_DepthReq<BaseClass>::StreamedDepthReq, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_DepthReq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DepthReq(::grpc::ServerContext* /*context*/, const ::depth::DepthRequest* /*request*/, ::depth::DepthRsP* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDepthReq(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::depth::DepthRequest,::depth::DepthRsP>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_DepthReq<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_DepthReq<Service > StreamedService;
};

}  // namespace depth


#endif  // GRPC_depth_2eproto__INCLUDED
