// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: depthStream.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_depthStream_2eproto__INCLUDED
#define GRPC_depthStream_2eproto__INCLUDED

#include "depthStream.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace depth {

// The greeting service definition.
class DepthStreamService final {
 public:
  static constexpr char const* service_full_name() {
    return "depth.DepthStreamService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    std::unique_ptr< ::grpc::ClientReaderInterface< ::depth::DepthStreamRsP>> DepthStreamReq(::grpc::ClientContext* context, const ::depth::DepthStreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::depth::DepthStreamRsP>>(DepthStreamReqRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::depth::DepthStreamRsP>> AsyncDepthStreamReq(::grpc::ClientContext* context, const ::depth::DepthStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::depth::DepthStreamRsP>>(AsyncDepthStreamReqRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::depth::DepthStreamRsP>> PrepareAsyncDepthStreamReq(::grpc::ClientContext* context, const ::depth::DepthStreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::depth::DepthStreamRsP>>(PrepareAsyncDepthStreamReqRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Sends a greeting
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void DepthStreamReq(::grpc::ClientContext* context, ::depth::DepthStreamRequest* request, ::grpc::ClientReadReactor< ::depth::DepthStreamRsP>* reactor) = 0;
      #else
      virtual void DepthStreamReq(::grpc::ClientContext* context, ::depth::DepthStreamRequest* request, ::grpc::experimental::ClientReadReactor< ::depth::DepthStreamRsP>* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderInterface< ::depth::DepthStreamRsP>* DepthStreamReqRaw(::grpc::ClientContext* context, const ::depth::DepthStreamRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::depth::DepthStreamRsP>* AsyncDepthStreamReqRaw(::grpc::ClientContext* context, const ::depth::DepthStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::depth::DepthStreamRsP>* PrepareAsyncDepthStreamReqRaw(::grpc::ClientContext* context, const ::depth::DepthStreamRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::depth::DepthStreamRsP>> DepthStreamReq(::grpc::ClientContext* context, const ::depth::DepthStreamRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::depth::DepthStreamRsP>>(DepthStreamReqRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::depth::DepthStreamRsP>> AsyncDepthStreamReq(::grpc::ClientContext* context, const ::depth::DepthStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::depth::DepthStreamRsP>>(AsyncDepthStreamReqRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::depth::DepthStreamRsP>> PrepareAsyncDepthStreamReq(::grpc::ClientContext* context, const ::depth::DepthStreamRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::depth::DepthStreamRsP>>(PrepareAsyncDepthStreamReqRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void DepthStreamReq(::grpc::ClientContext* context, ::depth::DepthStreamRequest* request, ::grpc::ClientReadReactor< ::depth::DepthStreamRsP>* reactor) override;
      #else
      void DepthStreamReq(::grpc::ClientContext* context, ::depth::DepthStreamRequest* request, ::grpc::experimental::ClientReadReactor< ::depth::DepthStreamRsP>* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReader< ::depth::DepthStreamRsP>* DepthStreamReqRaw(::grpc::ClientContext* context, const ::depth::DepthStreamRequest& request) override;
    ::grpc::ClientAsyncReader< ::depth::DepthStreamRsP>* AsyncDepthStreamReqRaw(::grpc::ClientContext* context, const ::depth::DepthStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::depth::DepthStreamRsP>* PrepareAsyncDepthStreamReqRaw(::grpc::ClientContext* context, const ::depth::DepthStreamRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_DepthStreamReq_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    virtual ::grpc::Status DepthStreamReq(::grpc::ServerContext* context, const ::depth::DepthStreamRequest* request, ::grpc::ServerWriter< ::depth::DepthStreamRsP>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_DepthStreamReq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DepthStreamReq() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_DepthStreamReq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DepthStreamReq(::grpc::ServerContext* /*context*/, const ::depth::DepthStreamRequest* /*request*/, ::grpc::ServerWriter< ::depth::DepthStreamRsP>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDepthStreamReq(::grpc::ServerContext* context, ::depth::DepthStreamRequest* request, ::grpc::ServerAsyncWriter< ::depth::DepthStreamRsP>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_DepthStreamReq<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_DepthStreamReq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_DepthStreamReq() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackServerStreamingHandler< ::depth::DepthStreamRequest, ::depth::DepthStreamRsP>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::depth::DepthStreamRequest* request) { return this->DepthStreamReq(context, request); }));
    }
    ~ExperimentalWithCallbackMethod_DepthStreamReq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DepthStreamReq(::grpc::ServerContext* /*context*/, const ::depth::DepthStreamRequest* /*request*/, ::grpc::ServerWriter< ::depth::DepthStreamRsP>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::depth::DepthStreamRsP>* DepthStreamReq(
      ::grpc::CallbackServerContext* /*context*/, const ::depth::DepthStreamRequest* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::depth::DepthStreamRsP>* DepthStreamReq(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::depth::DepthStreamRequest* /*request*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_DepthStreamReq<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_DepthStreamReq<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_DepthStreamReq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DepthStreamReq() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_DepthStreamReq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DepthStreamReq(::grpc::ServerContext* /*context*/, const ::depth::DepthStreamRequest* /*request*/, ::grpc::ServerWriter< ::depth::DepthStreamRsP>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_DepthStreamReq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DepthStreamReq() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_DepthStreamReq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DepthStreamReq(::grpc::ServerContext* /*context*/, const ::depth::DepthStreamRequest* /*request*/, ::grpc::ServerWriter< ::depth::DepthStreamRsP>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDepthStreamReq(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_DepthStreamReq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_DepthStreamReq() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const::grpc::ByteBuffer* request) { return this->DepthStreamReq(context, request); }));
    }
    ~ExperimentalWithRawCallbackMethod_DepthStreamReq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DepthStreamReq(::grpc::ServerContext* /*context*/, const ::depth::DepthStreamRequest* /*request*/, ::grpc::ServerWriter< ::depth::DepthStreamRsP>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* DepthStreamReq(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #else
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer>* DepthStreamReq(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)
    #endif
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_DepthStreamReq : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_DepthStreamReq() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler< ::depth::DepthStreamRequest, ::depth::DepthStreamRsP>(std::bind(&WithSplitStreamingMethod_DepthStreamReq<BaseClass>::StreamedDepthStreamReq, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithSplitStreamingMethod_DepthStreamReq() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DepthStreamReq(::grpc::ServerContext* /*context*/, const ::depth::DepthStreamRequest* /*request*/, ::grpc::ServerWriter< ::depth::DepthStreamRsP>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedDepthStreamReq(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::depth::DepthStreamRequest,::depth::DepthStreamRsP>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_DepthStreamReq<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_DepthStreamReq<Service > StreamedService;
};

}  // namespace depth


#endif  // GRPC_depthStream_2eproto__INCLUDED
