// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: depthStream.proto

#include "depthStream.pb.h"
#include "depthStream.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace depth {

static const char* DepthStreamService_method_names[] = {
  "/depth.DepthStreamService/DepthStreamReq",
};

std::unique_ptr< DepthStreamService::Stub> DepthStreamService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DepthStreamService::Stub> stub(new DepthStreamService::Stub(channel));
  return stub;
}

DepthStreamService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_DepthStreamReq_(DepthStreamService_method_names[0], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::depth::DepthStreamRsP>* DepthStreamService::Stub::DepthStreamReqRaw(::grpc::ClientContext* context, const ::depth::DepthStreamRequest& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::depth::DepthStreamRsP>::Create(channel_.get(), rpcmethod_DepthStreamReq_, context, request);
}

void DepthStreamService::Stub::experimental_async::DepthStreamReq(::grpc::ClientContext* context, ::depth::DepthStreamRequest* request, ::grpc::experimental::ClientReadReactor< ::depth::DepthStreamRsP>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::depth::DepthStreamRsP>::Create(stub_->channel_.get(), stub_->rpcmethod_DepthStreamReq_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::depth::DepthStreamRsP>* DepthStreamService::Stub::AsyncDepthStreamReqRaw(::grpc::ClientContext* context, const ::depth::DepthStreamRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::depth::DepthStreamRsP>::Create(channel_.get(), cq, rpcmethod_DepthStreamReq_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::depth::DepthStreamRsP>* DepthStreamService::Stub::PrepareAsyncDepthStreamReqRaw(::grpc::ClientContext* context, const ::depth::DepthStreamRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::depth::DepthStreamRsP>::Create(channel_.get(), cq, rpcmethod_DepthStreamReq_, context, request, false, nullptr);
}

DepthStreamService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DepthStreamService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< DepthStreamService::Service, ::depth::DepthStreamRequest, ::depth::DepthStreamRsP>(
          std::mem_fn(&DepthStreamService::Service::DepthStreamReq), this)));
}

DepthStreamService::Service::~Service() {
}

::grpc::Status DepthStreamService::Service::DepthStreamReq(::grpc::ServerContext* context, const ::depth::DepthStreamRequest* request, ::grpc::ServerWriter< ::depth::DepthStreamRsP>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace depth

